# AUTO_1 through 100
# PROTSEL1 through 250
# OUT101 through 116
# OUT201 through 216
# OUT301 through 316
# TMB1A through TMB8A
# BFI3P1
# BFIA1
# BFIB1
# BFIC1
# BFTR1
# BFI3P2
# BFIA2
# BFIB2
# BFIC2
# BFTR2
# TR
# TRCOMM
# TRSOTF
# DTA
# DTB
# DTC

COMMAND_LIST = [
/^AUTO_\S+/,
/^PROTSEL\S+/,
/^OUT1\S+/,
/^OUT2\S+/,
/^OUT3\S+/,
/^TMB\S+/,
/^BFI3P1\S+/,
/^BFIA1\S+/,
/^BFIB1\S+/,
/^BFIC1\S+/,
/^BFTR1\S+/,
/^BFI3P2\S+/,
/^BFIA2\S+/,
/^BFIB2\S+/,
/^BFIC2\S+/,
/^BFTR2\S+/,
/^TR\S+/,
/^TRCOMM\S+/,
/^TRSOTF\S+/,
/^DTA\S+/,
/^DTB\S+/,
/^DTC\S+/
]

text = "PROTSEL1  # <<<<<<< LINE INTENTIONALLY LEFT BLANK >>>>>>>
PROTSEL2  PSV01 := BFTRIP1 OR BFTRIP2 OR PCT15Q OR PCT14Q OR ASV042 OR M4PT OR 51S1T OR 51S2T OR IN303 OR IN304 #GENERAL TRIP, KEY 3 PH NON-RECLOSEABLE DTT. PCT14Q/PCT15Q ARE O/V PTN,  ASV042 IS OPEN POLE PTN, 51S1T AND 51S2T ARE CH. INDEP. GND O/C, M4PT IS TIME DELAYED CH. INDEP. PTN, IN303 IS 5RX4 PN, IN304 IS 5RX4 ISOL.
PROTSEL3  PSV02 := IN204 AND (M1P OR M2P AND COMPRM) OR IN206 AND 3PT OR IN207 AND NOT SPO AND SPLSHT AND 3PT # ONE ITEM IN 79DTL
PROTSEL4  PSV03 := PSV01 OR RMB6A #3 PH NON-RECLOSEABLE TRIP
PROTSEL5  PSV63 := NOT (SPO OR SPT)
OUT301             TPA1 OR ASV051 OR RTA1 OR PCT01Q OR PLT09 # TRIP 5CB4 PHASE A
TMB1A              IN308 AND PSV53 OR RB01 #PT KEY OUT. KEY INCLUDES ALL TERM OF TRCOMM EQ. 3PT IS 3 PHASE TRIP, 67 Q2 FOR ADDITIONAL KEY SENSITIVITY
TMB8A        IN308 AND (3PT OR 3PO OR IN105) OR RB08 # INDICATE LOCAL TERMINAL OPEN FOR RAS"

# Process individual lines
lines = text.lines
lines.each do |l|
  l.gsub!(/#.*/,"") # Remove comments
  COMMAND_LIST.each do |c|
    l.match(c) { |m| l.gsub!(m[0], m[0] + " := ") } # We matched a command, so make it a variable
  end
  l.strip!.squeeze!(' ') # Remove leading/trailing whitespace and doubled whitespace
  p l
end